# Generated by Django 5.2.14 on 2026-05-28 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(choices=[('CARD', 'CARDIO'), ('RES', 'RESISTANCE'), ('YO', 'YOGA'), ('HI', 'HIIT'), ('PIL', 'PILATES'), ('CROSS', 'CROSS-FIT'), ('STR', 'STRETCHING')], max_length=20)),
                ('level', models.CharField(choices=[('BEG', 'BEGINNER'), ('INT', 'INTERMEDIATE'), ('ADV', 'ADVANCED')], max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trainer')),
            ],
        ),
    ]
